[build-system]
requires = ["setuptools", "wheel", "setuptools_scm", "cython"]
build-backend = "setuptools.build_meta"

[black.tool]
line-length = 100

[tool.pytest.ini_options]
filterwarnings = [
    "error",
]
