[build-system]
requires = ["setuptools >=43", "wheel", "setuptools_scm>=6.2", "cython ~=0.29.20"]
build-backend = "setuptools.build_meta"

[black.tool]
line-length = 100

[tool.pytest.ini_options]
filterwarnings = [
    "error",
]

[tool.setuptools_scm]
write_to = "src/cutadapt/_version.py"
